# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
    push:
    pull_request:
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest
                cfg:
                    - Debug
                    - Release
        runs-on: ${{ matrix.os }}
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.0.0
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v2.0.0
            - name: Build project
              run: |
                  dotnet tool restore
                  dotnet publish -c ${{ matrix.cfg }}
            - name: Run samples
              run: |
                  dotnet example --all \
                      --skip cancellation \
                      --skip control \
                      --skip cursor \
                      --skip raw \
                      --skip scrolling \
                      --skip signals \
                      --skip width
            - name: Upload GitHub packages
              if: github.event_name == 'push' && github.repository == 'vezel-dev/cathode' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.cfg == 'Debug'
              run: |
                  dotnet tool run gpr push pkg/feed/*.nupkg -k ${{ secrets.GITHUB_TOKEN }}
            - name: Prune GitHub packages
              if: github.event_name == 'push' && github.repository == 'vezel-dev/cathode' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.cfg == 'Debug'
              uses: SmartsquareGmbH/delete-old-packages@v0.4.0
              with:
                  names: |
                      Cathode
                      Cathode.Analyzers
                      Cathode.Extensions
                      Cathode.Hosting
                  keep: 5
