# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prebuild
on:
    schedule:
        - cron: 0 6 * * *
    workflow_dispatch:
defaults:
    run:
        shell: bash
jobs:
    prebuild:
        if: github.repository == 'alexrp/cathode'
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.0.0
              with:
                  fetch-depth: 0
                  submodules: recursive
            - uses: github/codespaces-precache@v1.1.0
              with:
                  sku_name: standardLinux32gb
                  regions: EastUs SouthEastAsia WestEurope WestUs2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
