# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Release
on:
    release:
        types:
            - published
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
jobs:
    release:
        runs-on: windows-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
            - name: Extract .NET version
              id: dotnet
              run: |
                  echo ::set-output name=version::$(tail -n +2 global.json | jq .sdk.version -r)
            - name: Set up .NET
              uses: actions/setup-dotnet@v1.7.2
              with:
                  dotnet-version: ${{ steps.dotnet.outputs.version }}
            - name: Install dependencies
              run: |
                  dotnet tool restore
                  dotnet restore
            - name: Pack project
              run: |
                  dotnet pack -c Release --no-build
            - name: Upload GitHub packages
              if: github.repository == 'alexrp/system-terminal'
              run: |
                  DOTNET_ROLL_FORWARD=LatestMajor dotnet gpr push src/*/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }}
            - name: Upload NuGet packages
              if: github.repository == 'alexrp/system-terminal'
              run: |
                  dotnet nuget push src/*/bin/Release/*.{nupkg,snupkg} -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
